Issue 38. CartController + CRUD
GBTeamworks/gift_service pull request #48
Opened 2022-11-27 12:15 UTC by starmanSN

2022-11-29 18:47 UTC, Lezenford commented on src/main/java/com/giftservice/gift_service/controllers/CartController.java
> +        return "";
что то недописали

2022-11-29 18:47 UTC, Lezenford commented on src/main/java/com/giftservice/gift_service/entities/Cart.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE,
каскады в данном случае спорный вопрос - изменять подарки, общие для всех, из частной корзины это неверный подход к задаче и ошибка

2022-11-29 18:47 UTC, Lezenford commented on src/main/java/com/giftservice/gift_service/entities/Gift.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
аналогично. изменять корзины из подарка - плохой подход

2022-11-29 18:47 UTC, Lezenford commented on src/main/java/com/giftservice/gift_service/entities/Cart.java
> +    private String status = "not empty";
у вас есть enum с нужными данными. используйте его

2022-12-03 01:46 UTC, BigElmo requested changes
Подправить по замечаниям преподавателя на прошедшем занятии

2022-12-06 23:07 UTC, BigElmo approved these changes

2022-12-07 11:11 UTC, merged